server:
  port: 8080
  servlet:
    context-path: /smart-eyes
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jsjsjds?useUnicode=true&characterEncoding=utf-8&userSSl=true&serverTimezone=UTC
    username: root
    password: 132123
  data:
#    redis配置
    redis:
      host: 127.0.0.1
      database: 0
      port: 8888
      password:
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.smarteyes.domain
  map-underscore-to-camel-case: true